# netlify.toml — Vite + Vue 3 (SPA) on Netlify

[build]
  # Tumia ci kisha build (Netlify hutumia package-lock.json)
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# 🔒 ZIMA Netlify Asset Optimization / Post-processing (tunaamini Vite pekee)
[build.processing]
  skip_processing = true
  # — au tumia granular kama unataka —
  # [build.processing.css]
  #   bundle = false
  #   minify = false
  # [build.processing.js]
  #   bundle = false
  #   minify = false
  # [build.processing.images]
  #   compress = false

# ---------------- Redirects ----------------

# 1) Bundles/Assets zipite moja kwa moja (zisivunjwe na SPA fallback)
[[redirects]]
  from = "/assets/*"
  to   = "/assets/:splat"
  status = 200
  force = true

# 2) Faili za kawaida zipite moja kwa moja
[[redirects]]  # favicon
  from = "/favicon.ico"
  to   = "/favicon.ico"
  status = 200

[[redirects]]  # robots
  from = "/robots.txt"
  to   = "/robots.txt"
  status = 200

[[redirects]]  # sitemap
  from = "/sitemap.xml"
  to   = "/sitemap.xml"
  status = 200

# 3) SPA fallback kwa routes zote za app (muhimu kwa Vue Router history mode)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# ---------------- Headers ----------------

# A) Security headers kwa kurasa zote
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # ⚠️ CSP iliyoruhusu app yako kufanya kazi.
    # Ikiwa utatumia vyanzo maalum (CDN/API), ongeza kwenye connect-src/img-src/font-src n.k.
    Content-Security-Policy = "default-src 'self' data: blob: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: blob: https:; font-src 'self' data: https:; connect-src 'self' https: wss:; media-src 'self' data: blob: https:; frame-ancestors 'self'; base-uri 'self'"

# B) Usicache index.html (ili kupata deploy mpya mara moja)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"

# C) Cache kali kwa bundles zilizo na hash (salama sana)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # Fonts/CSS kutoka assets kuruhusu matumizi cross-origin (ikihitajika)
    Access-Control-Allow-Origin = "*"

# D) Service Worker (ikiwa unatumia /sw.js)
[[headers]]
  for = "/sw.js"
  [headers.values]
    Service-Worker-Allowed = "/"
    Cache-Control = "public, max-age=0, must-revalidate"

# E) Web App Manifest (hiari)
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=3600"
