# netlify.toml — Vite + Vue 3 (SPA) on Netlify

[build]
  command = "npm run build"
  publish = "dist"

  # Tumia Node 20 (au ile unayotumia kwenye local)
  [build.environment]
    NODE_VERSION = "20"

# ---------------- Redirects ----------------

# 1) Ruhusu bundles/asset zipitishwe moja kwa moja (zisiangukie SPA fallback)
[[redirects]]
  from = "/assets/*"
  to   = "/assets/:splat"
  status = 200
  force = true

# 2) Faili za kawaida (favicon/robots/sitemap) zipite moja kwa moja
[[redirects]]  # favicon
  from = "/favicon.ico"
  to   = "/favicon.ico"
  status = 200

[[redirects]]  # robots
  from = "/robots.txt"
  to   = "/robots.txt"
  status = 200

[[redirects]]  # sitemap
  from = "/sitemap.xml"
  to   = "/sitemap.xml"
  status = 200

# 3) SPA fallback kwa routes zote za app
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# ---------------- Headers ----------------

# A) Security headers kwa kurasa zote
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # CSP ya msamiati mpana (unaweza kuikaza kulingana na mahitaji ya API/CDN zako)
    Content-Security-Policy = "default-src 'self' data: blob: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: blob: https:; font-src 'self' data: https:; connect-src 'self' https: wss:; media-src 'self' data: blob: https:; frame-ancestors 'self'; base-uri 'self'"

# B) Usicache index.html (ili kupata deploy mpya mara moja)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"

# C) Cache kali kwa bundles zilizo na hash (salama)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# D) Cache fupi kwa manifest (hiari)
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=3600"
