# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# Single Page App fallback (Vue + Vite)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers kwa ukurasa wote
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Aggressive cache ya assets zilizofungwa na hash (vite)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
