# netlify.toml — SmartBiz (Vite + Vue 3 SPA) — DIRECT MODE (no /api proxy)

[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION      = "20"
  # Frontend iwasiliane moja kwa moja na backend (HAKUNA proxy ya /api/*)
  VITE_API_BASE     = "https://smartbiz-backend-p45m.onrender.com"
  VITE_APP_VERSION  = "1.0.0"
  # (hiari) timeout/retries (ikifaa na code yako ya api.ts)
  # VITE_API_TIMEOUT_MS   = "60000"
  # VITE_API_MAX_RETRIES  = "3"
  # VITE_API_CACHE_TTL_MS = "300000"

[forms]
  enabled = false

[build.processing]
  skip_processing = true

################################################################################
# Redirects
################################################################################

# SPA fallback (LAZIMA iwe mwisho)
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

# (hiari) Lazimisha HTTPS kwenye subdomain ya Netlify
[[redirects]]
  from   = "http://*smartbizsite.netlify.app/*"
  to     = "https://smartbizsite.netlify.app/:splat"
  status = 301
  force  = true

################################################################################
# Headers (Security + Caching)
################################################################################

# A) Usalama wa jumla + CSP yenye connect-src kwa backend ya Render
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options    = "nosniff"
    X-Frame-Options           = "DENY"
    Referrer-Policy           = "strict-origin-when-cross-origin"
    Permissions-Policy        = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # ⚠ Badilisha URL hapa ukibadilisha backend.
    Content-Security-Policy = """
      default-src 'self' https: data: blob:;
      script-src  'self' 'unsafe-inline' https:;
      style-src   'self' 'unsafe-inline' https:;
      img-src     'self' https: data: blob:;
      font-src    'self' https: data:;
      connect-src 'self' https://smartbiz-backend-p45m.onrender.com https:;
      media-src   'self' https: data: blob:;
      worker-src  'self' blob:;
      frame-ancestors 'self';
      base-uri 'self';
      form-action 'self'
    """

# B) index.html: isicache (ili deploy mpya zionekane papo hapo)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"

# C) Bundles zenye hash: cache ndefu
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# D) Sourcemaps (hiari)
[[headers]]
  for = "/assets/*.map"
  [headers.values]
    Content-Type  = "application/json"
    Cache-Control = "public, max-age=3600"

# E) Manifest & favicon
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"
